# Generated by Django 4.1 on 2022-08-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmHospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HosGoo', models.CharField(max_length=20)),
                ('HosDong', models.CharField(max_length=20)),
                ('HosName', models.CharField(max_length=50)),
                ('AlwaysTime', models.IntegerField()),
                ('HosAddress', models.CharField(max_length=50)),
                ('HosSNA', models.CharField(max_length=50)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
            ],
        ),
    ]
