# Generated by Django 4.1 on 2022-08-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boolvalue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boolvalue',
            name='BeautyTrue',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='boolvalue',
            name='CafeTrue',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='boolvalue',
            name='Hos24True',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='boolvalue',
            name='HospitalTrue',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='boolvalue',
            name='HotelTrue',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='boolvalue',
            name='ParkTrue',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='boolvalue',
            name='TaxiTrue',
            field=models.BooleanField(blank=True),
        ),
    ]
