# Generated by Django 4.1 on 2022-08-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InfraGoo', models.CharField(max_length=20)),
                ('InfraDong', models.CharField(max_length=20)),
                ('InfraWork', models.CharField(max_length=20)),
                ('InfraName', models.CharField(max_length=50)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
            ],
        ),
    ]
