# Generated by Django 4.1 on 2022-08-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ParkGoo', models.CharField(max_length=20)),
                ('ParkDong', models.CharField(max_length=20)),
                ('ParkName', models.CharField(max_length=50)),
                ('ParkType', models.CharField(max_length=20)),
                ('ParkAddress', models.CharField(max_length=50)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('ParkArea', models.IntegerField()),
                ('AreaPart', models.IntegerField()),
            ],
        ),
    ]
